#!/usr/bin/python3
# amarok_compress Copyright (c) 2012 Stuart Pook (http://www.pook.it/)
# extract files from amarok 2.x and compress FLAC files
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
import subprocess, sys, os
import tempfile 

class MyError(Exception):
	pass
	
def nice():
	os.nice(10)

def main():
#	parser = optparse.OptionParser()
#	parser.disable_interspersed_args()	
#	parser.add_option("-v", "--verbose", action="store_true", help="verbose message")
#	(options, args) = parser.parse_args()
#		if len(args) != 0:
#		parser.error("must supply 0 arguments")

	root = "/disks/shared/music"
	c1 = ["amarok_extract", "--strip", "." + root + "/"]
	file_list = tempfile.TemporaryFile()
	subprocess.check_call(c1, stdout=file_list)
		
	file_list.seek(0)
	
	c2 = [ "transform", "--quiet", "--max_filename_characters=63", "--delete", "--list" ]
#	if options.verbose:
#		c2.append("--verbose")
		
	c2.extend(sys.argv[1:])
	c2.append(root)
	c2.append("/disks/ws/stuart/compressed_music")
	
	subprocess.check_call(c2, stdin=file_list, preexec_fn=nice)

if __name__ == "__main__":
	main()
