#!/usr/bin/python
import subprocess, sys, os
def main():
	cr2 =["sudo", "debian-user",
		"dcraw -c -w -h -p " +
			os.path.expanduser("~/lib/ICC/Canon_400D/Standard.icc") + " " +
			"/dev/stdin"]
	jpeg = ["cjpeg", "-quality", "90", "-progressive", "-scale", "1/2"]
	#print >> sys.stderr, " ".join(cr2)
	dcraw = subprocess.Popen(cr2, stdout=subprocess.PIPE)
	cjpeg = subprocess.Popen(jpeg, stdin=dcraw.stdout)
	dcraw.stdout.close()
	dcraw.wait()
	cjpeg.wait()
	if dcraw.returncode != 0 or cjpeg.returncode != 0:
		return 1
	return 0
if __name__ == "__main__":
	sys.exit(main())
