#!/usr/bin/python
# cr2-to-jpeg, Copyright (c) 2012 Stuart Pook (http://www.pook.it/)
# convert a CR2 file from a Canon EOS 400D into a jpeg file.

# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# must work with python 2.5
import subprocess, sys, os
def main():
	cr2 =["sudo", "debian-user",
		"dcraw -c -w -h -p " +
			os.path.expanduser("~/lib/ICC/Canon_400D/Standard.icc") + " " +
			"/dev/stdin"]
	jpeg = ["cjpeg", "-quality", "90", "-progressive", "-scale", "1/2"]
	#print >> sys.stderr, " ".join(cr2)
	dcraw = subprocess.Popen(cr2, stdout=subprocess.PIPE)
	cjpeg = subprocess.Popen(jpeg, stdin=dcraw.stdout)
	dcraw.stdout.close()
	dcraw.wait()
	cjpeg.wait()
	if dcraw.returncode != 0 or cjpeg.returncode != 0:
		return 1
	return 0
if __name__ == "__main__":
	sys.exit(main())
