#!/usr/bin/python3
# lockscreen4bed Copyright (c) 2016 Stuart Pook (http://www.pook.it/)
# set noexpandtab copyindent preserveindent softtabstop=0 shiftwidth=4 tabstop=4
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
import argparse
import sys
import os
import subprocess
from apscheduler.schedulers.blocking import BlockingScheduler

def myname():
    return os.path.basename(sys.argv[0])

def verbose(options, level, *message):
    if options.verbosity >= level:
        print(myname() + ":", *message, file=sys.stderr)

def call(cmd, options=None):
    verbose(options, 1, cmd)
    subprocess.check_call(cmd)

def doit(options=None):
    call(["xset", "dpms", "force", "off"], options=options)
    call(["gnome-screensaver-command", "--lock"], options=options)

def main():
    parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter,
            description="send me to bed")

    parser.add_argument("-v", "--verbosity", action="count", default=0, help="increase output verbosity")
    #parser.add_argument("--min_play_time", metavar="SECONDS", type=int, default=9, help="minimum")
    parser.add_argument("-m", "--minutes", metavar="MINUTES", default="14,29,44,59", help="minutes in cron format")
    #parser.add_argument('-a', "--add", action="store_true", help="add podcast urls to list")
    #parser.add_argument("--loop", action="store_true", help="play all podcasts")

    parser.add_argument('urls', nargs=argparse.REMAINDER, help='urls to (permanently) add to the play list')

    options = parser.parse_args()

    cron = BlockingScheduler()
    cron.add_job(doit, kwargs={'options': options}, trigger='cron', hour="0-4,22-23", minute=options.minutes)
    cron.start()


if __name__ == "__main__":
    main()
