#!/usr/bin/python3
# photo-directory-archive, Copyright (C) 2013 Stuart Pook (http://www.pook.it/)
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os, optparse, sys, errno, subprocess
import hashlib
import tempfile

def myname():
	return os.path.basename(sys.argv[0])

def get_best_snapshot_with_album(album, snapshots, options):
	best_set = frozenset()
	best_snapshot = None
	for snapshot in snapshots:
		dir = os.path.join(options.snapshots, snapshot, album)
		try:
			files = os.listdir(dir)
		except OSError as e:
			if e.errno != errno.ENOENT:
				raise
			continue
		cr3 = frozenset([i for i in files if i.endswith(options.photo_suffix)])
		if cr3 > best_set:
			best_set = cr3
			best_snapshot = snapshot
		elif not cr3 <= best_set:
			sys.error("%s: for album %s snapshot %s has gained (%s) and lost photos from %s: %s" % (myname(), album, snapshot, (cr3 - best_set), best_snapshot, (best_set - cr3)))
	if best_snapshot is None:
		sys.error(myname() + ": no snapshot contained" + album)
	return best_snapshot, best_set

def get_first_snapshot_with_album(album, snapshots, options):
	for snapshot in snapshots:
		dir = os.path.join(options.snapshots, snapshot, album)
		try:
			files = os.listdir(dir)
			if len(files) > 0:
				return snapshot, files
		except OSError as e:
			if e.errno != errno.ENOENT:
				raise
				
	sys.exit(os.path.basename(sys.argv[0]) + ": album '" + album + "' not found in snapshots '" + options.snapshots + "'")
	
def getsize(path, options):
	sz = os.path.getsize(path) 
	r = (sz + options.block_size - 1) // options.block_size
	#print (path, sz, r)
	return r

def do_album(album, snapshots, options):
	snapshot, photos  = get_best_snapshot_with_album(album, snapshots, options)
	
	files = []
	
	for file in photos:
		files.append([album + "/" + file, os.path.join(options.snapshots, snapshot, album, file)])
	
	current_dir = os.path.join(options.photos, album)
	for file in os.listdir(current_dir):
		if file.endswith(options.photo_suffix):
			if not options.force:
				assert file in photos, "photo " + file + " not in snapshot " + snapshot + " for " + album + " " + str(photos)
		elif file.endswith(options.rawtherapee_suffix):
			if not options.force:
				assert file[0:-len(options.rawtherapee_suffix)] + options.photo_suffix in photos, "pp3 " + file + " not in snapshot " + snapshot + " for " + album
			files.append([album + "/" + file, os.path.join(current_dir, file)])

	sz = 0
	for file in files:
		sz += getsize(file[1], options)

	return sz, files
	
def do_md5sum(filenames, tmp, options):
	for name, file in filenames:
		with open(file, "rb") as data:
			m = hashlib.md5()
			while True:
				s = data.read(1024 * 8)
				if not s:
					break
				m.update(s)
			v = "%s *%s" % (m.hexdigest(), name)
			if options.verbose > 1:
				print(v)
			print(v, file=tmp)
	
def main():	
	parser = optparse.OptionParser(usage="%prog [--help] [options] album ...")
	parser.disable_interspersed_args()
	
	parser.add_option("-K", "--keep_MD5", action="store_true", help="leave MD5 file in /tmp")
	parser.add_option("-x", "--execute", action="store_true", help="make DVD")
	parser.add_option("-f", "--force", action="store_true", help="don't check that all photos are present")
	parser.add_option("-q", "--quiet", action="store_true", help="no messages")
	parser.add_option("-v", "--verbose", action="count", default=0, help="verbosity")
	parser.add_option("-V", "--volid", help="volume name")
	parser.add_option("-n", "--dryrun", default=False, action="store_true", help="do not execute")
	parser.add_option("--snapshots", default="/disks/snapshots/photos", help="snapshots [%default]")
	parser.add_option("--photos", default=os.path.expanduser("~/photos"), help="directory containing albums [%default]")
	parser.add_option("--photo_suffix", default=".cr2", help="photo suffix [%default]")
	parser.add_option("--block_size", type='int', default=2048, help="block size for space calculations [%default]")
	parser.add_option("--dvd_size", type='int', default=4700 * 1000 * 1000, help="DVD size for space calculations [%default]")
	parser.add_option("-2", "--dual_layer", action="store_const", const=8540 * 1000 * 1000, dest='dvd_size', help="dual layer DVD size for space calculations")
	parser.add_option("--rawtherapee_suffix", default=".cr2.pp3", help="rawtherapee suffix [%default]")
	parser.add_option("--command", default="dvdmake", help="command to create a DVD [%default]")

	(options, args) = parser.parse_args()
	
	if not args:
		parser.error("must have at least on album")
		
	volid = None
	if len(args) == 1:
		volid = args[0]
	if options.volid:
		volid = options.volid
	if not volid:
		parser.error("must use the --volid option when more than one album")
	
	snapshots = os.listdir(options.snapshots)
	snapshots.sort()
		
	command = [ options.command, "-V", options.volid, "-graft-points" ]
	
	filenames = []
	
	used = 0
	for i in args:
		sz, names = do_album(i, snapshots, options)
		if (used + sz) * options.block_size >= options.dvd_size:
			if used == 0:
				sys.exit(myname() +": no space for first album: " + i)
			if not options.quiet:
				print("no more space for", i)
		else:
			used += sz
			filenames.extend(names)
			if not options.quiet:
				print(i, sz, "sectors", len(names), "files")
		
	for name, file in filenames:
		command.append(name+ "=" + file)
	
	bytes = used * options.block_size
	if not options.quiet:
		print(used, "sectors,", bytes, "bytes,", "%.1f %%" % (bytes * 100 / options.dvd_size))
		
	if options.execute or options.verbose:
		with tempfile.NamedTemporaryFile(mode='w', prefix='photo-directory-archive', delete=(not options.keep_MD5)) as md5:
			do_md5sum(filenames, md5, options)
			command.append("md5sums.txt=" + md5.name)
			if options.verbose:
				print(command)
			if options.execute:
				subprocess.check_call(command)

if __name__ == "__main__":
	main()
