#!/usr/bin/python3
# run_when_killed, Copyright (C) 2013 Stuart Pook (http://www.pook.it/)
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import time
import optparse
import os

def go(args,  options):
	if options.fork and os.fork():
		return
	pid = os.fork()
	if pid:
		os.chdir("/")
		for fd in range(0, 100):
			try:
				os.close(fd)
			except OSError:
				pass
		for i in range(3):
			os.open("/dev/null", os.O_RDWR)
		os.waitpid(pid,  0)
		os.execvp(args[0], args)
	time.sleep(60 * 60 * 24 * 365)

def main():	
	parser = optparse.OptionParser(usage="%prog [--help] [options] command ...")
	parser.disable_interspersed_args()
	
	parser.add_option("-f", "--fork", action="store_true", help="fork")

	(options, args) = parser.parse_args()
	
	if not args:
		parser.error("need a command to run")

	go(args,  options)

if __name__ == '__main__':
	main()
