#!/usr/bin/python3
# sync-photos-nexus7 Copyright (c) 2013 Stuart Pook (http://www.pook.it/)
# Send the correct photos to my nexus 7.
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import optparse
import os
import subprocess
import shlex

def main():
	parser = optparse.OptionParser(usage="usage: %prog [options] [--help] [machine]")
	parser.add_option("--machine", default="windy", help="where to send to [%default]")
	parser.add_option("-s", "--source_dir", default="/disks/scratch/stuart/converted-photos2", help="source directory [%default]")
	parser.add_option("--dest_dir", default="/storage/sdcard1/Stuart_Pook/rsync", help="destination directory [%default]")
	parser.add_option("-v", "--verbose", action="store_true", help="verbose")
	parser.add_option("-n", "--norun", action="store_true", help="don't run the rsync")
	parser.add_option("-S", "--size", help="size [%default]")
	parser.add_option("--rsync-path", default=None, help="remote rsync path [%default]")
	parser.add_option("--size-only", action="store_const", const="--size-only", dest="compare")
	parser.add_option("--times", action="store_const", const="--times", default="--size-only", dest="compare")
	(options, args) = parser.parse_args()

	if len(args) > 1:
		parser.error("only 1 argument allowed")
	machine = args[0] if len(args) else options.machine
	size = options.size if options.size else machine

	cmd = ["rsync"]
	if options.rsync_path:
		cmd.append("--rsync-path=" + options.rsync_path)
	cmd.extend(["--exclude", "#*"])
	cmd.append("--copy-unsafe-links")
	cmd.append(options.compare)
	cmd.append("--delete")
	cmd.append("-Pr")
	cmd.append(os.path.join(options.source_dir, size) + "/")
	cmd.append(machine + ":" + os.path.join(options.dest_dir, "photos-sync/"))
	if options.verbose or options.norun:
		print(" ".join(shlex.quote(c) for c in cmd))
	if not options.norun:
		subprocess.check_call(cmd)
		subprocess.check_call(["ssh", "-n", options.machine, "am broadcast android.intent.action.MEDIA_MOUNTED"])

if __name__ == "__main__":
	main()
