#!/usr/bin/python2.5
# tunnel_home Copyright (c) 2012 Stuart Pook (http://www.pook.it/)
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
from __future__ import with_statement

import os, optparse

def main():
	parser = optparse.OptionParser()
	parser.disable_interspersed_args()
	
	parser.add_option("-H", "--host", help = "host to connect to [%default]", default="sftp")
	parser.add_option("-v", "--verbose", action="store_true", dest="verbose", default=False)
	
	(options, args) = parser.parse_args()
	
	forwards = [ 143, 587 ]
	args = ["ssh", "-Nnax" ]
	for p in forwards:
		args.extend(["-L", "%d:localhost:%s" % (10000 + p, p)])
	args.append(options.host)
	
	os.execvp(args[0], args)
	
if __name__ == "__main__":
	main()
